version: "3.9"
services:
  security-app:
    depends_on: 
      - database
    image: iliaisakhin/security-application:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_PASSWORD: changeme
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
  database:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/database:/docker-entrypoint-initdb.d
