CREATE TABLE IF NOT EXISTS users (username VARCHAR PRIMARY KEY, password VARCHAR, enabled BOOLEAN);
CREATE TABLE IF NOT EXISTS authorities (id serial PRIMARY KEY, username VARCHAR, authority VARCHAR, CONSTRAINT fk_authorities FOREIGN KEY(username) REFERENCES users(username));
CREATE UNIQUE INDEX ix_auth_username ON authorities (username,authority);

--create table groups (
--	id bigint generated by default as identity(start with 0) primary key,
--	group_name varchar_ignorecase(50) not null
--);
--
--create table group_authorities (
--	group_id bigint not null,
--	authority varchar(50) not null,
--	constraint fk_group_authorities_group foreign key(group_id) references groups(id)
--);
--
--create table group_members (
--	id bigint generated by default as identity(start with 0) primary key,
--	username varchar(50) not null,
--	group_id bigint not null,
--	constraint fk_group_members_group foreign key(group_id) references groups(id)
--);
